### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by sourcier**
Depends on: https://github.com/sourcier/friendly-broccoli/pull/9

### CODE REVIEW

**Comment by breenie** [comment]
Yo @sourcier can you resolve these conflicts? Cheers babes.

**Review by breenie — CHANGES_REQUESTED** [review]
Is there some reason why the year is hardcoded and not something like `new Date().getFullYear()`?

**Comment by sourcier** [comment]
> Is there some reason why the year is hardcoded and not something like `new Date().getFullYear()`?

Yes, there is, the general rule is that the year to include in a copyright notice is the year of first publication of the work.

**Review by breenie — APPROVED** [review]
Understood cap'n!

**Pull request merged**
